version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-npm: false
          install-yarn: false
          node-version: '12.6.0'
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn format-check
